// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiplayerGames_Server.Infrastructure.SignalR.Persistence.Data;

#nullable disable

namespace MultiplayerGames_Server.Infrastructure.SignalR.Migrations
{
    [DbContext(typeof(SignalRDbContext))]
    [Migration("20260609202220_SomeChanges")]
    partial class SomeChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OnlineXO_Server.Infrastructure.SignalR.DataModels.HubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("HubGroups");
                });

            modelBuilder.Entity("OnlineXO_Server.Infrastructure.SignalR.DataModels.HubGroupUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("HubGroupUsers");
                });

            modelBuilder.Entity("OnlineXO_Server.Infrastructure.SignalR.DataModels.HubGroupUser", b =>
                {
                    b.HasOne("OnlineXO_Server.Infrastructure.SignalR.DataModels.HubGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
