<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\DomainServices\" />
    <Folder Include="Aggregates\Otp\" />
    <Folder Include="Aggregates\RefreshToken\" />
    <Folder Include="Aggregates\Test\" />
    <Folder Include="Aggregates\User\" />
    <Folder Include="Aggregates\XOGame\" />
    <Folder Include="Common\" />
    <Folder Include="Common\Codes\" />
    <Folder Include="Common\Constants\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="DependencyInjection\" />
    <Folder Include="Services\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
  </ItemGroup>
</Project>
