<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnlineXO_Server.Application\OnlineXO_Server.Application.csproj" />
    <ProjectReference Include="..\OnlineXO_Server.Domain\OnlineXO_Server.Domain.csproj" />
    <ProjectReference Include="..\OnlineXO_Server.Infrastructure.SignalR\OnlineXO_Server.Infrastructure.SignalR.csproj" />
    <ProjectReference Include="..\OnlineXO_Server.Infrastructure\OnlineXO_Server.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Controllers\" />
    <Folder Include="DependencyInjection\" />
    <Folder Include="Middlewares\" />
  </ItemGroup>

</Project>
